# This config represents a ReID only configuration of DeepSORT, it has two uses.
# One is used for loading the detection results and ReID model to get tracking results;
# Another is used for exporting the ReID model to deploy infer.

_BASE_: [
  '../../mot/deepsort/reid/deepsort_pplcnet_vehicle.yml'
]

num_classes: 1

EvalMOTDataset:
  !MOTImageFolder
    dataset_dir: dataset/mtmct
    data_root: S01/images
    keep_ori_im: True # set as True in DeepSORT

det_weights: None
reid_weights: weights/reid_best_model.pdparams

# architecture: MTMCT_DeepSort

# config for mtmc
score_thr: 0.1
USE_FF: False
USE_RERANK: False
# REID_SIZE_TEST: [384, 384]
cameras_bias:
  c001: 0
  c002: 0
  c003: 0
  c004: 0
  c005: 0










